name: 'Deploy Terraform Configuration'

on:
  push:
    branches:
      - main  # Trigger on changes to the main branch
  pull_request:
    branches:
      - main  # Optionally trigger on pull requests for validation

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    # Set up environment variables and retrieve secrets
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}  # Retrieved from GitHub Secrets

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: '1.8.2'  # Specify your desired Terraform version

    - name: Initialize Terraform
      run: terraform init
      working-directory: terrform/ecs-alb  # Corrected to match your actual directory spelling

    - name: Apply Terraform
      run: terraform apply --auto-approve
      working-directory: terrform/ecs-alb  # Corrected to match your actual directory spelling
